"use client";

import { useState } from "react";
import useSWR from "swr";

function isStoreAdmin(session) { const roles=[...(session?.user?.roles||[]),session?.user?.role].map((value)=>String(value||"").toLowerCase()); return roles.some((role)=>["administrator","shop_manager","store_admin"].includes(role)); }
async function load(url,session){const response=await fetch(url,{headers:{"x-nevari-frontend-origin":window.location.origin,"x-nevari-frontend-type":session.frontendType}});const result=await response.json();if(!response.ok||!result?.success)throw new Error(result?.error?.message||"Unable to load IV requests.");return result.data;}

export default function IvTherapyOperationsPanel({session}){
  const admin=isStoreAdmin(session); const [selectedId,setSelectedId]=useState(""); const [clinicianId,setClinicianId]=useState(""); const [scheduledAt,setScheduledAt]=useState(""); const [notes,setNotes]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const base=new URLSearchParams({baseUrl:session?.baseUrl||"",per_page:"50"});
  const requestsQuery=useSWR(session?.baseUrl?`/api/admin/care-iv?${base}`:null,(url)=>load(url,session));
  const cliniciansQuery=useSWR(admin&&session?.baseUrl?`/api/admin/users?${new URLSearchParams({baseUrl:session.baseUrl,role:"pharmacist",status:"approved",per_page:"50"})}`:null,(url)=>load(url,session));
  const requests=requestsQuery.data?.items||[]; const selected=requests.find((item)=>String(item.id)===String(selectedId)); const clinicians=cliniciansQuery.data?.items||[];
  async function transition(status){if(!selected)return;setBusy(true);setMessage("");try{const payload={baseUrl:session.baseUrl,status,patient_safe_message:status==="approved"?"Your IV Therapy request was clinically approved.":"Your IV Therapy request status was updated."};if(clinicianId)payload.clinician_user_id=Number(clinicianId);if(scheduledAt)payload.scheduled_at=new Date(scheduledAt).toISOString();if(notes)payload.clinical={review_notes:notes};const response=await fetch(`/api/admin/care/iv-therapy/${selected.id}`,{method:"PATCH",headers:{"content-type":"application/json","x-nevari-frontend-origin":window.location.origin,"x-nevari-frontend-type":session.frontendType},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok||!result?.success)throw new Error(result?.error?.message||"Unable to update IV request.");setMessage("IV Therapy request updated.");await requestsQuery.mutate();}catch(error){setMessage(error.message);}finally{setBusy(false);}}
  return <section className="panel iv-operations-panel"><div className="panel-header"><div><p className="section-kicker">{admin?"Operational review":"Assigned clinical review"}</p><h2>{admin?"IV Therapy operations":"My IV Therapy cases"}</h2></div></div>{message?<p className="receipt-feedback" role="status">{message}</p>:null}{requestsQuery.error?<p className="form-error">{requestsQuery.error.message}</p>:null}<div className="iv-operations-list">{requestsQuery.isLoading?<p>Loading requests…</p>:requests.length?requests.map((item)=><button type="button" className={`iv-operation-row ${String(item.id)===String(selectedId)?"active":""}`} key={item.id} onClick={()=>{setSelectedId(String(item.id));setClinicianId(String(item.assignee?.id||""));}}><span><strong>{item.reference}</strong><small>{item.patient?.name}</small></span><span>{item.status_label}</span><span>{item.assignee?.name||"Unassigned"}</span></button>):<p className="muted">No assigned IV Therapy requests.</p>}</div>{selected?<div className="iv-operation-editor"><h3>{selected.reference}</h3>{admin?<label><span>Assigned pharmacist</span><select value={clinicianId} onChange={(event)=>setClinicianId(event.target.value)}><option value="">Select pharmacist</option>{clinicians.map((item)=><option key={item.user_id} value={item.user_id}>{item.display_name}</option>)}</select></label>:<label><span>Clinical review notes</span><textarea value={notes} onChange={(event)=>setNotes(event.target.value)} maxLength={5000}/></label>}<label><span>Schedule</span><input type="datetime-local" value={scheduledAt} onChange={(event)=>setScheduledAt(event.target.value)}/></label><div className="governed-user-actions">{admin?<><button type="button" className="pill-button" disabled={busy||selected.status!=="submitted"||!clinicianId} onClick={()=>transition("under_review")}>Assign for review</button><button type="button" className="button-primary" disabled={busy||selected.status!=="approved"||!scheduledAt} onClick={()=>transition("scheduled")}>Confirm schedule</button></>:<><button type="button" className="button-primary" disabled={busy||selected.status!=="under_review"} onClick={()=>transition("approved")}>Approve clinically</button><button type="button" className="pill-button danger" disabled={busy||selected.status!=="under_review"} onClick={()=>transition("declined")}>Decline</button><button type="button" className="button-primary" disabled={busy||selected.status!=="scheduled"} onClick={()=>transition("treatment_completed")}>Treatment completed</button><button type="button" className="button-primary" disabled={busy||selected.status!=="treatment_completed"} onClick={()=>transition("completed")}>Close case</button></>}</div></div>:null}</section>;
}
